### ISSUE TITLE
Door types

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/homebridge-homeseer#35] opened 2018-03-30 14:48 UTC
So I am trying to add my Door contact sensor (ZWave Fibaro Device) into the system.

This seems to work...

			   {
				"ref":3768,
				"type":"ContactSensor",
				"name":"Porch Door Status",
				"batteryRef":3769,
			    "batteryThreshold":0
				}

However...its correctly not declared as a Door Type in HomeKit. I can't seem to use...

			   {
				"ref":3768,
				"type":"Door",
				"name":"Porch Door Status"
                           }

as it declares it an invalid type. Am I doing anything wrong here?

**Comment by jvmahon** [comment] 2018-03-30 14:59
Add it as a "ContactSensor" as you did in your first example.   Then after starting homebridge, go to your "Porch Door Status" icon as shown in the iOS Home app. Give a long-press to get to the "Details" page and select the "Details" button. About half-way down the next page, there is a label "Type" which will indicate "Contact Sensor" by default. Press on that Type label and you can then change the contact sensor to indicate its a "Door", "Window", etc.

Also, its unusual to set batteryThreshold to 0. At this level, you won't get a low-battery warning. I'd recommend something closer to 20. The only reason I can think of to have the batteryThreshold at 0 is if the device is powered by USB or other non-battery source.

As a FYI - there is a "Door" type in HomeKit but that's generally for use with a motorized door to  open/close it. Motorized doors are not implemented in this plugin.

**Comment by jvmahon** [comment] 2018-03-30 15:41
No problem. I also added a Wiki page for the next person who asks. . . 
https://github.com/jvmahon/homebridge-homeseer/wiki/Contact-Sensor-Icon-Type-(Door,-Window,-etc.)
As for the battery, if the problem is in the HomeSeer side, I'm not sure what you can do about it.  The plugin expects HomeSeer to report something between 0 - 100. If HomeSeer isn't doing that, the only thing I can suggest is to try and delete the Contact Sensor device from HomeSeer entirely, and then re-adding it in the hopes that HomeSeer corrects the battery.

This being said, HomeSeer also seems to have problems with batteries in my Schlage locks, so this just may be something that HomeSeer has to work on. Battery reporting used to work correctly, now HomeSeer always reports 100% (the plugin has no way of influencing this so its not the plugin side). I'm using the latest beta of HomeSeer and its Z-Wave plugin, so HomeSeer seems to be the issue.

Since this seems to be resolved, I'm closing this comment. Best regards. Jim

**Closed by jvmahon** 2018-03-30 15:41 UTC
