### ISSUE TITLE
Is there a maximum number of items that can be put in the config.json file?

### ISSUE THREAD

**Issue by grpalmer** [jvmahon/homebridge-homeseer#61] opened 2018-09-17 18:20 UTC
I have been building up my config.json file, and I suddenly ran into an issue.  I added a single switch to the file, saved it, and then when I attempted to restart home bridge, I received the following error:

[2018-9-17 12:00:52] [HomeSeer] bold is not defined.

The JSON file is fine, and passes JSONLint.  Now, what is very interesting, is if I remove the new Switch, everything is fine.  In fact, if I remove another device, everything is fine.  I just seems like I have hit some kind of max value in the file.  

I currently have the following:

1 Bridge
1 Platform
49 Lightbulbs (using the "lightbulbs" type)
13 Events
38 Accessories (Consisting of: Switch, Lightbulb, Fan, Thermostat, Lock, HumiditySensor, TemperatureSensor, ContactSensor and SecuritySystem.)

This currently totals 100 events/devices that are being registered.  When I attempt to add an additional event or accessory, Homebridge fails on restart with the above message.

Is it coincidental that the going from 100 to 101 entries causes the system to fail, or is this some kind of a limitation built into the home bridge application or the home bridge-homeseer plugin?

Please advise at your earliest possible convenience.

Thanks,

George

**Comment by jvmahon** [comment] 2018-09-17 18:26
Yes, there is a maximum of about 100.  This is a HomeKit limitation - no  bridge can support more than 100 bridged devices.  The solution is to divide your config.json into two files and run them as two separate bridges. I've found that the system actually responds better that way anyway.  I've divided mine into one bridge for lighting  (dimmers / switches), a second bridge for everything else.

**Comment by grpalmer** [comment] 2018-09-17 18:27
I just found the note on the Homebridge page that confirms this

**Comment by jvmahon** [comment] 2018-09-17 18:28
Are you using LInux or Windows?  I posted a comment to another forum one time that explained in some more detail about dividing up the config.json file. I can try and find that for you. I thought I had put a note about this in my Wiki, but can't seem to find that at the moment.

**Comment by grpalmer** [comment] 2018-09-17 18:29
By the way, this plugin, along with homebridge is Awesome!  It has become the single biggest use for my Apple Watch! LOL!  I am running home bridge and the plugin on a Raspberry PI 3+

**Comment by grpalmer** [comment] 2018-09-17 18:30
That would be fantastic!  I have spent about 3 hours on this issue.  I didn't realize that this limitation existed, and kept banging my head against the wall.  Then it dawned on me that my current total was 100, and that leads me to where I am today.

**Comment by jvmahon** [comment] 2018-09-17 18:32
I found the post. Here's how to do it (I'll also add info. to  my Wiki):

Simply divide your config.json file into two or more files each named config.json but which are then stored in different directories. As an example, create two directories /var/homebridge/instance1 and /var/homebridge/instance2 . Into each of these directories, place a config.json file with less than 100 accessories. Also, make sure that you change the bridge's "username" and port number in the second config.json file so it does not match the first config.json. For example, use ports 51828 and 51829. Also, on Linux, make sure the two directories have full rwx permissions. Now just start two instances of homebridge using the -U option to specify the two different folders (instead of relying on the default). I.e., execute:

homebridge -U /var/homebridge/instance1

homebridge -U /var/homebridge/instance2

This will then create two bridges, each of which can have up to 100 accessories. You'll have to add them as two separate pairings to the Home app, but once that's done, you're all set.

**Comment by grpalmer** [comment] 2018-09-17 18:34
I am not sure what you mean by; "You'll have to add them as two separate pairings to the Home app."  Please elaborate a bit on that for me.

**Comment by jvmahon** [comment] 2018-09-17 18:37
When you use homebridge, you set up a config.json and then run homebridge. When it is run, it displays a QR code or a PIN number. On the iPhone's Home app, you then scan the QR code or enter the PIN number to pair the bridge with the iPhone. After you've done that, you see all your accessories.

Now, as you'll be running two separate instances of homebridge, you will have to repeat this process for the second instance of homebridge. I.e., you'll set up a second homebridge bridge and pair that with the Home app by scanning  its QR code or entering its PIN.

**Comment by grpalmer** [comment] 2018-09-17 18:39
OH, duh!  That's pretty simple.  Sorry, I should have realized that when I read your comment.  I will give that a go, and see if I can get things working.  Again, thanks for a great plugin.

**Comment by jvmahon** [comment] 2018-09-17 18:43
You're welcome. Glad you are finding the plugin helpful. It was the first piece of software I have written in JavaScript and probably the first major software undertaking I've done in more than 20 years!

**Comment by grpalmer** [comment] 2018-09-17 18:45
One last question.....You mentioned that I would have to change the username and port for the second instance.  Do I need to change the pin as well?  What would I change the username (and pin if required) to for the second instance?  I thought those were supplied, but its been a while since I installed this, so I may be mistaken.

**Comment by jvmahon** [comment] 2018-09-17 18:48
I'm 99% certain you can use the same PIN.; but no harm changing it just in case.  But it is critical  to change the port  / username - I just increment them both by 1.

**Comment by grpalmer** [comment] 2018-09-17 18:49
OK, sounds good.  I will give that a try tonight when am back at home.

**Comment by jvmahon** [comment] 2018-09-27 15:19
Since there have been no more post, I assume the issue is resolve and so am closing the issue.

**Closed by jvmahon** 2018-09-27 15:19 UTC
